export const AUTH_ERROR = "AUTH_ERROR";

export const USER_REQUESTED = "USER_REQUESTED";
export const USER_LOADED = "USER_LOADED";

export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const ERRORS_RETURNED = "ERRORS_RETURNED";
export const ERRORS_CLEARED = "ERRORS_CLEARED";

export const SESSION_REQUESTED = "SESSION_REQUESTED";
export const SESSION_ERROR = "SESSION_ERROR";
export const SESSION_CREATED = "SESSION_CREATED";
export const SESSION_FETCHED = "SESSION_FETCHED";
export const SESSION_RETURNED = "SESSION_RETURNED";
export const SESSION_UPDATED = "SESSION_UPDATED";
export const SESSION_DELETED = "SESSION_DELETED";